apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage
  namespace: default
spec:
  secretName: backstage-secret
  dnsNames:
    - zf.backstage.new.trainings.nvtc.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer